# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.Trip')),
            ],
        ),
    ]
